project_id = "xiqhaiyieisgemqopxfw"

[functions.register-postcard]
verify_jwt = false


[functions.generate-qr]
verify_jwt = false

[functions.generate-qr-pdf]
verify_jwt = false

[functions.p24-webhook]
verify_jwt = false

[functions.issue-fiscal-document]
verify_jwt = false

[functions.fiscal-document-pdf]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.inpost-shipx-webhook]
verify_jwt = false

[functions.confirm-cod-payment]
verify_jwt = true
