-- Seed all world countries into public.countries table
INSERT INTO public.countries (iso2, iso3, name_pl, slug, active)
VALUES
  ('AF', 'AFG', 'Afganistan', 'afganistan', true),
  ('AL', 'ALB', 'Albania', 'albania', true),
  ('DZ', 'DZA', 'Algieria', 'algieria', true),
  ('AD', 'AND', 'Andora', 'andora', true),
  ('AO', 'AGO', 'Angola', 'angola', true),
  ('AG', 'ATG', 'Antigua i Barbuda', 'antigua-i-barbuda', true),
  ('SA', 'SAU', 'Arabia Saudyjska', 'arabia-saudyjska', true),
  ('AR', 'ARG', 'Argentyna', 'argentyna', true),
  ('AM', 'ARM', 'Armenia', 'armenia', true),
  ('AU', 'AUS', 'Australia', 'australia', true),
  ('AT', 'AUT', 'Austria', 'austria', true),
  ('AZ', 'AZE', 'Azerbejdżan', 'azerbejdzan', true),
  ('BS', 'BHS', 'Bahamy', 'bahamy', true),
  ('BH', 'BHR', 'Bahrajn', 'bahrajn', true),
  ('BD', 'BGD', 'Bangladesz', 'bangladesz', true),
  ('BB', 'BRB', 'Barbados', 'barbados', true),
  ('BE', 'BEL', 'Belgia', 'belgia', true),
  ('BZ', 'BLZ', 'Belize', 'belize', true),
  ('BJ', 'BEN', 'Benin', 'benin', true),
  ('BT', 'BTN', 'Bhutan', 'bhutan', true),
  ('BY', 'BLR', 'Białoruś', 'bialorus', true),
  ('BO', 'BOL', 'Boliwia', 'boliwia', true),
  ('BA', 'BIH', 'Bośnia i Hercegowina', 'bosnia-i-hercegowina', true),
  ('BW', 'BWA', 'Botswana', 'botswana', true),
  ('BR', 'BRA', 'Brazylia', 'brazylia', true),
  ('BN', 'BRN', 'Brunei', 'brunei', true),
  ('BG', 'BGR', 'Bułgaria', 'bulgaria', true),
  ('BF', 'BFA', 'Burkina Faso', 'burkina-faso', true),
  ('BI', 'BDI', 'Burundi', 'burundi', true),
  ('CL', 'CHL', 'Chile', 'chile', true),
  ('CN', 'CHN', 'Chiny', 'chiny', true),
  ('HR', 'HRV', 'Chorwacja', 'chorwacja', true),
  ('CY', 'CYP', 'Cypr', 'cypr', true),
  ('TD', 'TCD', 'Czad', 'czad', true),
  ('ME', 'MNE', 'Czarnogóra', 'czarnogora', true),
  ('CZ', 'CZE', 'Czechy', 'czechy', true),
  ('DK', 'DNK', 'Dania', 'dania', true),
  ('CD', 'COD', 'Demokratyczna Republika Konga', 'demokratyczna-republika-konga', true),
  ('DM', 'DMA', 'Dominika', 'dominika', true),
  ('DO', 'DOM', 'Dominikana', 'dominikana', true),
  ('DJ', 'DJI', 'Dżibuti', 'dzibuti', true),
  ('EG', 'EGY', 'Egipt', 'egipt', true),
  ('EC', 'ECU', 'Ekwador', 'ekwador', true),
  ('ER', 'ERI', 'Erytrea', 'erytrea', true),
  ('EE', 'EST', 'Estonia', 'estonia', true),
  ('SZ', 'SWZ', 'Eswatini', 'eswatini', true),
  ('ET', 'ETH', 'Etiopia', 'etiopia', true),
  ('FJ', 'FJI', 'Fidżi', 'fidzi', true),
  ('PH', 'PHL', 'Filipiny', 'filipiny', true),
  ('FI', 'FIN', 'Finlandia', 'finlandia', true),
  ('FR', 'FRA', 'Francja', 'francja', true),
  ('GA', 'GAB', 'Gabon', 'gabon', true),
  ('GM', 'GMB', 'Gambia', 'gambia', true),
  ('GH', 'GHA', 'Ghana', 'ghana', true),
  ('GR', 'GRC', 'Grecja', 'grecja', true),
  ('GD', 'GRD', 'Grenada', 'grenada', true),
  ('GE', 'GEO', 'Gruzja', 'gruzja', true),
  ('GY', 'GUY', 'Gujana', 'gujana', true),
  ('GT', 'GTM', 'Gwatemala', 'gwatemala', true),
  ('GN', 'GIN', 'Gwinea', 'gwinea', true),
  ('GW', 'GNB', 'Gwinea Bissau', 'gwinea-bissau', true),
  ('GQ', 'GNQ', 'Gwinea Równikowa', 'gwinea-rownikowa', true),
  ('HT', 'HTI', 'Haiti', 'haiti', true),
  ('ES', 'ESP', 'Hiszpania', 'hiszpania', true),
  ('NL', 'NLD', 'Holandia', 'holandia', true),
  ('HN', 'HND', 'Honduras', 'honduras', true),
  ('IN', 'IND', 'Indie', 'indie', true),
  ('ID', 'IDN', 'Indonezja', 'indonezja', true),
  ('IQ', 'IRQ', 'Irak', 'irak', true),
  ('IR', 'IRN', 'Iran', 'iran', true),
  ('IE', 'IRL', 'Irlandia', 'irlandia', true),
  ('IS', 'ISL', 'Islandia', 'islandia', true),
  ('IL', 'ISR', 'Izrael', 'izrael', true),
  ('JM', 'JAM', 'Jamajka', 'jamajka', true),
  ('JP', 'JPN', 'Japonia', 'japonia', true),
  ('YE', 'YEM', 'Jemen', 'jemen', true),
  ('JO', 'JOR', 'Jordania', 'jordania', true),
  ('KH', 'KHM', 'Kambodża', 'kambodza', true),
  ('CM', 'CMR', 'Kamerun', 'kamerun', true),
  ('CA', 'CAN', 'Kanada', 'kanada', true),
  ('QA', 'QAT', 'Katar', 'katar', true),
  ('KZ', 'KAZ', 'Kazachstan', 'kazachstan', true),
  ('KE', 'KEN', 'Kenia', 'kenia', true),
  ('KG', 'KGZ', 'Kirgistan', 'kirgistan', true),
  ('KI', 'KIR', 'Kiribati', 'kiribati', true),
  ('CO', 'COL', 'Kolumbia', 'kolumbia', true),
  ('KM', 'COM', 'Komory', 'komory', true),
  ('CG', 'COG', 'Kongo', 'kongo', true),
  ('KR', 'KOR', 'Korea Południowa', 'korea-poludniowa', true),
  ('KP', 'PRK', 'Korea Północna', 'korea-polnocna', true),
  ('XK', 'XKX', 'Kosowo', 'kosowo', true),
  ('CR', 'CRI', 'Kostaryka', 'kostaryka', true),
  ('CU', 'CUB', 'Kuba', 'kuba', true),
  ('KW', 'KWT', 'Kuwejt', 'kuwejt', true),
  ('LA', 'LAO', 'Laos', 'laos', true),
  ('LS', 'LSO', 'Lesotho', 'lesotho', true),
  ('LB', 'LBN', 'Liban', 'liban', true),
  ('LR', 'LBR', 'Liberia', 'liberia', true),
  ('LY', 'LBY', 'Libia', 'libia', true),
  ('LI', 'LIE', 'Liechtenstein', 'liechtenstein', true),
  ('LT', 'LTU', 'Litwa', 'litwa', true),
  ('LU', 'LUX', 'Luksemburg', 'luksemburg', true),
  ('LV', 'LVA', 'Łotwa', 'lotwa', true),
  ('MK', 'MKD', 'Macedonia Północna', 'macedonia-polnocna', true),
  ('MG', 'MDG', 'Madagaskar', 'madagaskar', true),
  ('MW', 'MWI', 'Malawi', 'malawi', true),
  ('MV', 'MDV', 'Malediwy', 'malediwy', true),
  ('MY', 'MYS', 'Malezja', 'malezja', true),
  ('ML', 'MLI', 'Mali', 'mali', true),
  ('MT', 'MLT', 'Malta', 'malta', true),
  ('MA', 'MAR', 'Maroko', 'maroko', true),
  ('MH', 'MHL', 'Wyspy Marshalla', 'wyspy-marshalla', true),
  ('MR', 'MRT', 'Mauretania', 'mauretania', true),
  ('MU', 'MUS', 'Mauritius', 'mauritius', true),
  ('MX', 'MEX', 'Meksyk', 'meksyk', true),
  ('FM', 'FSM', 'Mikronezja', 'mikronezja', true),
  ('MD', 'MDA', 'Mołdawia', 'moldawia', true),
  ('MC', 'MCO', 'Monako', 'monako', true),
  ('MN', 'MNG', 'Mongolia', 'mongolia', true),
  ('MZ', 'MOZ', 'Mozambik', 'mozambik', true),
  ('MM', 'MMR', 'Mjanma (Birma)', 'mjanma', true),
  ('NA', 'NAM', 'Namibia', 'namibia', true),
  ('NR', 'NRU', 'Nauru', 'nauru', true),
  ('NP', 'NPL', 'Nepal', 'nepal', true),
  ('DE', 'DEU', 'Niemcy', 'niemcy', true),
  ('NE', 'NER', 'Niger', 'niger', true),
  ('NG', 'NGA', 'Nigeria', 'nigeria', true),
  ('NI', 'NIC', 'Nikaragua', 'nikaragua', true),
  ('NO', 'NOR', 'Norwegia', 'norwegia', true),
  ('NZ', 'NZL', 'Nowa Zelandia', 'nowa-zelandia', true),
  ('OM', 'OMN', 'Oman', 'oman', true),
  ('PK', 'PAK', 'Pakistan', 'pakistan', true),
  ('PW', 'PLW', 'Palau', 'palau', true),
  ('PS', 'PSE', 'Palestyna', 'palestyna', true),
  ('PA', 'PAN', 'Panama', 'panama', true),
  ('PG', 'PNG', 'Papua-Nowa Gwinea', 'papua-nowa-gwinea', true),
  ('PY', 'PRY', 'Paragwaj', 'paragwaj', true),
  ('PE', 'PER', 'Peru', 'peru', true),
  ('PL', 'POL', 'Polska', 'polska', true),
  ('PT', 'PRT', 'Portugalia', 'portugalia', true),
  ('ZA', 'ZAF', 'RPA', 'rpa', true),
  ('CF', 'CAF', 'Republika Środkowoafrykańska', 'republika-srodkowoafrykanska', true),
  ('CV', 'CPV', 'Republika Zielonego Przylądka', 'republika-zielonego-przyladka', true),
  ('RU', 'RUS', 'Rosja', 'rosja', true),
  ('RO', 'ROU', 'Rumunia', 'rumunia', true),
  ('RW', 'RWA', 'Ruanda', 'ruanda', true),
  ('KN', 'KNA', 'Saint Kitts i Nevis', 'saint-kitts-i-nevis', true),
  ('LC', 'LCA', 'Saint Lucia', 'saint-lucia', true),
  ('VC', 'VCT', 'Saint Vincent i Grenadyny', 'saint-vincent-i-grenadyny', true),
  ('SV', 'SLV', 'Salwador', 'salwador', true),
  ('WS', 'WSM', 'Samoa', 'samoa', true),
  ('SM', 'SMR', 'San Marino', 'san-marino', true),
  ('SN', 'SEN', 'Senegal', 'senegal', true),
  ('RS', 'SRB', 'Serbia', 'serbia', true),
  ('SC', 'SYC', 'Seszele', 'seszele', true),
  ('SL', 'SLE', 'Sierra Leone', 'sierra-leone', true),
  ('SG', 'SGP', 'Singapur', 'singapur', true),
  ('SK', 'SVK', 'Słowacja', 'slowacja', true),
  ('SI', 'SVN', 'Słowenia', 'slowenia', true),
  ('SO', 'SOM', 'Somalia', 'somalia', true),
  ('LK', 'LKA', 'Sri Lanka', 'sri-lanka', true),
  ('US', 'USA', 'Stany Zjednoczone', 'stany-zjednoczone', true),
  ('SD', 'SDN', 'Sudan', 'sudan', true),
  ('SS', 'SSD', 'Sudan Południowy', 'sudan-poludniowy', true),
  ('SR', 'SUR', 'Surinam', 'surinam', true),
  ('SY', 'SYR', 'Syria', 'syria', true),
  ('CH', 'CHE', 'Szwajcaria', 'szwajcaria', true),
  ('SE', 'SWE', 'Szwecja', 'szwecja', true),
  ('TJ', 'TJK', 'Tadżykistan', 'tadzykistan', true),
  ('TH', 'THA', 'Tajlandia', 'tajlandia', true),
  ('TW', 'TWN', 'Tajwan', 'tajwan', true),
  ('TZ', 'TZA', 'Tanzania', 'tanzania', true),
  ('TL', 'TLS', 'Timor Wschodni', 'timor-wschodni', true),
  ('TG', 'TGO', 'Togo', 'togo', true),
  ('TO', 'TON', 'Tonga', 'tonga', true),
  ('TT', 'TTO', 'Trynidad i Tobago', 'trynidad-i-tobago', true),
  ('TN', 'TUN', 'Tunezja', 'tunezja', true),
  ('TR', 'TUR', 'Turcja', 'turcja', true),
  ('TM', 'TKM', 'Turkmenistan', 'turkmenistan', true),
  ('TV', 'TUV', 'Tuvalu', 'tuvalu', true),
  ('UG', 'UGA', 'Uganda', 'uganda', true),
  ('UA', 'UKR', 'Ukraina', 'ukraina', true),
  ('UY', 'URY', 'Urugwaj', 'urugwaj', true),
  ('UZ', 'UZB', 'Uzbekistan', 'uzbekistan', true),
  ('VU', 'VUT', 'Vanuatu', 'vanuatu', true),
  ('VA', 'VAT', 'Watykan', 'watykan', true),
  ('HU', 'HUN', 'Węgry', 'wegry', true),
  ('VE', 'VEN', 'Wenezuela', 'wenezuela', true),
  ('GB', 'GBR', 'Wielka Brytania', 'wielka-brytania', true),
  ('VN', 'VNM', 'Wietnam', 'wietnam', true),
  ('IT', 'ITA', 'Włochy', 'wlochy', true),
  ('CI', 'CIV', 'Wybrzeże Kości Słoniowej', 'wybrzeze-kosci-sloniowej', true),
  ('SB', 'SLB', 'Wyspy Salomona', 'wyspy-salomona', true),
  ('ST', 'STP', 'Wyspy Świętego Tomasza i Książęca', 'wyspy-swietego-tomasza-i-ksiazeca', true),
  ('ZM', 'ZMB', 'Zambia', 'zambia', true),
  ('ZW', 'ZWE', 'Zimbabwe', 'zimbabwe', true),
  ('AE', 'ARE', 'Zjednoczone Emiraty Arabskie', 'zjednoczone-emiraty-arabskie', true),
  ('AX', 'ALA', 'Wyspy Alandzkie', 'wyspy-alandzkie', true),
  ('AS', 'ASM', 'Samoa Amerykańskie', 'samoa-amerykanskie', true),
  ('AI', 'AIA', 'Anguilla', 'anguilla', true),
  ('AW', 'ABW', 'Aruba', 'aruba', true),
  ('BM', 'BMU', 'Bermudy', 'bermudy', true),
  ('VG', 'VGB', 'Brytyjskie Wyspy Dziewicze', 'brytyjskie-wyspy-dziewicze', true),
  ('KY', 'CYM', 'Kajmany', 'kajmany', true),
  ('CW', 'CUW', 'Curaçao', 'curacao', true),
  ('FO', 'FRO', 'Wyspy Owcze', 'wyspy-owcze', true),
  ('GF', 'GUF', 'Gujana Francuska', 'gujana-francuska', true),
  ('PF', 'PYF', 'Polinezja Francuska', 'polinezja-francuska', true),
  ('GI', 'GIB', 'Gibraltar', 'gibraltar', true),
  ('GL', 'GRL', 'Grenlandia', 'grenlandia', true),
  ('GP', 'GLP', 'Gwadelupa', 'gwadelupa', true),
  ('GU', 'GUM', 'Guam', 'guam', true),
  ('HK', 'HKG', 'Hongkong', 'hongkong', true),
  ('IM', 'IMN', 'Wyspa Man', 'wyspa-man', true),
  ('JE', 'JEY', 'Jersey', 'jersey', true),
  ('GG', 'GGY', 'Guernsey', 'guernsey', true),
  ('MO', 'MAC', 'Makau', 'makau', true),
  ('MQ', 'MTQ', 'Martynika', 'martynika', true),
  ('YT', 'MYT', 'Majotta', 'majotta', true),
  ('NC', 'NCL', 'Nowa Kaledonia', 'nowa-kaledonia', true),
  ('PR', 'PRI', 'Portoryko', 'portoryko', true),
  ('RE', 'REU', 'Reunion', 'reunion', true),
  ('BL', 'BLM', 'Saint-Barthélemy', 'saint-barthelemy', true),
  ('MF', 'MAF', 'Saint-Martin', 'saint-martin', true),
  ('PM', 'SPM', 'Saint-Pierre i Miquelon', 'saint-pierre-i-miquelon', true),
  ('SX', 'SXM', 'Sint Maarten', 'sint-marneen', true),
  ('TC', 'TCA', 'Turks i Caicos', 'turks-i-caicos', true),
  ('VI', 'VIR', 'Wyspy Dziewicze USA', 'wyspy-dziewicze-usa', true)
ON CONFLICT (iso2) DO UPDATE SET
  iso3 = EXCLUDED.iso3,
  name_pl = EXCLUDED.name_pl,
  slug = EXCLUDED.slug,
  active = EXCLUDED.active;
