param(
  [string]$InputPath = (Join-Path $PSScriptRoot '..\supabase\baselines\DEV_PUBLIC_SCHEMA_FROM_REMOTE.sql'),
  [string]$OutputPath = (Join-Path $PSScriptRoot '..\supabase\baselines\DEV_PUBLIC_SCHEMA_BASELINE.sql')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $InputPath)) {
  throw "Remote public schema dump not found: $InputPath"
}

$sql = Get-Content -Raw -Path $InputPath

# pg_dump serializes ownership and session settings from DEV. Supabase owns the
# platform roles; application migrations must not try to recreate ownership.
$sql = $sql -replace '(?m)^SET (?!check_function_bodies).*?;\r?\n', ''
$sql = $sql -replace '(?m)^SELECT pg_catalog\.set_config\(.*?;\r?\n', ''
$sql = $sql -replace '(?ms)^CREATE SCHEMA IF NOT EXISTS "public";\r?\n\r?\nALTER SCHEMA "public" OWNER TO "pg_database_owner";\r?\n\r?\nCOMMENT ON SCHEMA "public" IS .*?;\r?\n\r?\n', ''
$sql = $sql -replace '(?m)^ALTER (TYPE|TABLE|FUNCTION|VIEW|SEQUENCE) .*? OWNER TO .*?;\r?\n', ''
$sql = $sql -replace '(?m)^ALTER SCHEMA "public" OWNER TO .*?;\r?\n', ''

# Keep pg_dump's original function-before-table ordering. The retained
# check_function_bodies setting is what lets PostgreSQL create functions that
# reference a table declared later in the same baseline.

$header = @"
-- Canonical DEV public schema baseline.
-- Source: schema-only export from xiqhaiyieisgemqopxfw on 2026-08-07.
-- Generated by scripts/build-final-dev-baseline.ps1.
-- This file contains schema, RLS, functions, views, triggers and grants only.
-- It does not contain application data or country dictionary seed data.
-- Do not add to supabase/migrations until it passes the empty-project test.

"@

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null
Set-Content -Path $OutputPath -Value ($header + $sql.Trim() + "`n") -Encoding utf8
Write-Output "Generated canonical baseline: $OutputPath"
