-- Canonical DEV public schema baseline.
-- Source: schema-only export from xiqhaiyieisgemqopxfw on 2026-08-07.
-- Generated by scripts/build-final-dev-baseline.ps1.
-- This file contains schema, RLS, functions, views, triggers and grants only.
-- It does not contain application data or country dictionary seed data.
-- Do not add to supabase/migrations until it passes the empty-project test.
SET check_function_bodies = false;


CREATE SCHEMA IF NOT EXISTS "public";




COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE TYPE "public"."app_role" AS ENUM (
    'traveler',
    'admin'
);




CREATE TYPE "public"."business_status" AS ENUM (
    'purchased',
    'registered'
);




CREATE TYPE "public"."event_actor_type" AS ENUM (
    'system',
    'admin',
    'traveler',
    'recipient'
);




CREATE TYPE "public"."fulfillment_status" AS ENUM (
    'in_stock',
    'reserved',
    'qr_generated',
    'qr_applied',
    'shipped',
    'voided',
    'damaged'
);




CREATE TYPE "public"."inventory_event_type" AS ENUM (
    'created_in_stock',
    'reserved_for_order',
    'qr_generated',
    'qr_applied',
    'shipped',
    'registered',
    'voided',
    'damaged'
);




CREATE TYPE "public"."order_status" AS ENUM (
    'pending',
    'paid',
    'fulfilled',
    'cancelled'
);




CREATE TYPE "public"."payment_status" AS ENUM (
    'unpaid',
    'paid',
    'refunded',
    'failed'
);




CREATE TYPE "public"."qr_print_job_status" AS ENUM (
    'pending',
    'generating',
    'ready',
    'printed',
    'failed'
);




CREATE TYPE "public"."shipment_status" AS ENUM (
    'pending',
    'packed',
    'shipped',
    'delivered',
    'returned'
);






CREATE TABLE IF NOT EXISTS "public"."recipient_registrations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "inventory_unit_id" "uuid" NOT NULL,
    "recipient_name" "text" NOT NULL,
    "recipient_message" "text",
    "recipient_email" "text",
    "contact_opt_in" boolean DEFAULT false NOT NULL,
    "registered_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "latitude" numeric,
    "longitude" numeric,
    "registered_country_iso2" "text"
);




CREATE OR REPLACE FUNCTION "public"."admin_list_recipient_registrations"() RETURNS SETOF "public"."recipient_registrations"
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Forbidden';
  END IF;
  RETURN QUERY SELECT * FROM public.recipient_registrations;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."calculate_distance"("lat1" numeric, "lon1" numeric, "lat2" numeric, "lon2" numeric) RETURNS numeric
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO 'public'
    AS $$
DECLARE
  r numeric := 6371;
  dlat numeric;
  dlon numeric;
  a numeric;
  c numeric;
BEGIN
  dlat := radians(lat2 - lat1);
  dlon := radians(lon2 - lon1);
  a := sin(dlat / 2) ^ 2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ^ 2;
  c := 2 * atan2(sqrt(a), sqrt(1 - a));
  RETURN round(r * c);
END;
$$;




CREATE OR REPLACE FUNCTION "public"."calculate_user_impact_points"("_user_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _unit_count int;
  _unique_countries int;
  _reg_count int;
  _total int;
  _rank text;
  _ppu int;
  _ppc int;
  _ppr int;
BEGIN
  -- Dynamically fetch scoring config
  SELECT points_per_unit, points_per_country, points_per_registration
  INTO _ppu, _ppc, _ppr
  FROM public.gamification_config
  WHERE id = 1;

  -- Fallback defaults
  _ppu := COALESCE(_ppu, 10);
  _ppc := COALESCE(_ppc, 50);
  _ppr := COALESCE(_ppr, 100);

  SELECT
    COUNT(*)::int,
    COUNT(DISTINCT cd.country_id)::int
  INTO _unit_count, _unique_countries
  FROM public.inventory_units iu
  JOIN public.card_designs cd ON cd.id = iu.card_design_id
  WHERE iu.traveler_user_id = _user_id;

  SELECT COUNT(*)::int INTO _reg_count
  FROM public.recipient_registrations rr
  JOIN public.inventory_units iu ON iu.id = rr.inventory_unit_id
  WHERE iu.traveler_user_id = _user_id;

  _total := (_unit_count * _ppu) + (_unique_countries * _ppc) + (_reg_count * _ppr);

  -- Dynamically determine rank from gamification_tiers
  SELECT name INTO _rank
  FROM public.gamification_tiers
  WHERE min_points <= _total
  ORDER BY min_points DESC
  LIMIT 1;

  _rank := COALESCE(_rank, 'Zwiadowca');

  UPDATE public.profiles
  SET total_points = _total,
      current_rank = _rank
  WHERE user_id = _user_id;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."create_order"("_items" "jsonb", "_pickup_point_name" "text", "_pickup_point_address" "text", "_pickup_point_city" "text", "_shipping_cost" numeric, "_invoice_requested" boolean DEFAULT false, "_company_name" "text" DEFAULT NULL::"text", "_company_nip" "text" DEFAULT NULL::"text", "_company_address" "text" DEFAULT NULL::"text", "_payment_method" "text" DEFAULT 'online'::"text", "_shipping_method" "text" DEFAULT 'inpost'::"text", "_shipping_name" "text" DEFAULT NULL::"text", "_shipping_street" "text" DEFAULT NULL::"text", "_shipping_postal_code" "text" DEFAULT NULL::"text", "_shipping_city" "text" DEFAULT NULL::"text", "_shipping_phone" "text" DEFAULT NULL::"text") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $_$
DECLARE
  _uid uuid := auth.uid(); _order_id uuid; _order_number text; _item jsonb; _design_id uuid; _qty int;
  _unit_price numeric(10,2); _price_grosze int; _total numeric(10,2) := 0; _nip_clean text;
  _expected_shipping numeric(10,2); _phone_clean text; _customer_email text := lower(trim(coalesce(auth.jwt() ->> 'email', '')));
BEGIN
  IF _uid IS NULL THEN RAISE EXCEPTION 'unauthorized'; END IF;
  IF _customer_email = '' OR _customer_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' THEN RAISE EXCEPTION 'customer_email_unavailable'; END IF;
  IF _items IS NULL OR jsonb_typeof(_items) <> 'array' OR jsonb_array_length(_items) = 0 THEN RAISE EXCEPTION 'empty_cart'; END IF;
  IF jsonb_array_length(_items) > 100 THEN RAISE EXCEPTION 'too_many_items'; END IF;
  IF _shipping_method IS NULL OR _shipping_method NOT IN ('inpost','courier') THEN RAISE EXCEPTION 'invalid_shipping_method'; END IF;
  IF _shipping_method = 'inpost' THEN
    IF coalesce(length(trim(_pickup_point_name)), 0) = 0 THEN RAISE EXCEPTION 'pickup_point_required'; END IF;
    _shipping_name := NULL; _shipping_street := NULL; _shipping_postal_code := NULL; _shipping_city := NULL; _shipping_phone := NULL;
  ELSE
    IF coalesce(length(trim(_shipping_name)), 0) = 0 THEN RAISE EXCEPTION 'shipping_name_required'; END IF;
    IF coalesce(length(trim(_shipping_street)), 0) = 0 THEN RAISE EXCEPTION 'shipping_street_required'; END IF;
    IF coalesce(length(trim(_shipping_postal_code)), 0) = 0 THEN RAISE EXCEPTION 'shipping_postal_code_required'; END IF;
    IF _shipping_postal_code !~ '^[0-9]{2}-[0-9]{3}$' THEN RAISE EXCEPTION 'shipping_postal_code_invalid'; END IF;
    IF coalesce(length(trim(_shipping_city)), 0) = 0 THEN RAISE EXCEPTION 'shipping_city_required'; END IF;
    _phone_clean := regexp_replace(coalesce(_shipping_phone, ''), '[^0-9+]', '', 'g');
    IF length(_phone_clean) < 9 OR length(_phone_clean) > 15 THEN RAISE EXCEPTION 'shipping_phone_invalid'; END IF;
    _shipping_phone := _phone_clean; _pickup_point_name := NULL; _pickup_point_address := NULL; _pickup_point_city := NULL;
  END IF;
  IF _payment_method IS NULL OR _payment_method NOT IN ('online','cod') THEN RAISE EXCEPTION 'invalid_payment_method'; END IF;
  _expected_shipping := CASE WHEN _payment_method = 'online' THEN 13.99 ELSE 16.99 END;
  IF _shipping_cost IS NULL OR _shipping_cost <> _expected_shipping THEN RAISE EXCEPTION 'invalid_shipping_cost'; END IF;
  IF _invoice_requested THEN
    IF coalesce(length(trim(_company_name)), 0) = 0 THEN RAISE EXCEPTION 'invoice_company_name_required'; END IF;
    IF coalesce(length(trim(_company_address)), 0) = 0 THEN RAISE EXCEPTION 'invoice_company_address_required'; END IF;
    _nip_clean := regexp_replace(coalesce(_company_nip, ''), '[^0-9]', '', 'g');
    IF NOT public.is_valid_nip(_nip_clean) THEN RAISE EXCEPTION 'invoice_nip_invalid'; END IF;
  ELSE _company_name := NULL; _company_nip := NULL; _company_address := NULL; _nip_clean := NULL; END IF;
  FOR _item IN SELECT * FROM jsonb_array_elements(_items) LOOP
    _design_id := (_item->>'card_design_id')::uuid; _qty := (_item->>'quantity')::int;
    IF _qty IS NULL OR _qty < 1 OR _qty > 1000 THEN RAISE EXCEPTION 'invalid_quantity'; END IF;
    SELECT price_grosze INTO _price_grosze FROM public.card_designs WHERE id = _design_id AND active = true AND price_grosze > 0;
    IF _price_grosze IS NULL THEN RAISE EXCEPTION 'invalid_design:%', _design_id; END IF;
    _unit_price := _price_grosze::numeric / 100.0; _total := _total + (_qty * _unit_price);
  END LOOP;
  _total := _total + _shipping_cost;
  INSERT INTO public.orders(user_id,total_amount,pickup_point_name,pickup_point_address,pickup_point_city,shipping_cost,invoice_requested,company_name,company_nip,company_address,payment_method,shipping_method,shipping_name,shipping_address,shipping_postal_code,shipping_city,shipping_country,shipping_phone,customer_email)
  VALUES (_uid,_total,_pickup_point_name,_pickup_point_address,_pickup_point_city,_shipping_cost,_invoice_requested,_company_name,_nip_clean,_company_address,_payment_method,_shipping_method,_shipping_name,_shipping_street,_shipping_postal_code,_shipping_city,CASE WHEN _shipping_method = 'courier' THEN 'Polska' ELSE NULL END,_shipping_phone,_customer_email)
  RETURNING id, order_number INTO _order_id, _order_number;
  FOR _item IN SELECT * FROM jsonb_array_elements(_items) LOOP
    _design_id := (_item->>'card_design_id')::uuid; _qty := (_item->>'quantity')::int;
    SELECT price_grosze INTO _price_grosze FROM public.card_designs WHERE id = _design_id;
    _unit_price := _price_grosze::numeric / 100.0;
    INSERT INTO public.order_items(order_id,card_design_id,quantity,unit_price,total_price) VALUES (_order_id,_design_id,_qty,_unit_price,_qty * _unit_price);
  END LOOP;
  RETURN jsonb_build_object('id',_order_id,'order_number',_order_number,'total_amount',_total,'payment_method',_payment_method,'shipping_method',_shipping_method);
END;
$_$;




CREATE OR REPLACE FUNCTION "public"."generate_claim_code"() RETURNS "text"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  code TEXT;
  cnt INTEGER;
  chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  i INTEGER;
  part1 TEXT := '';
  part2 TEXT := '';
BEGIN
  LOOP
    part1 := '';
    part2 := '';
    FOR i IN 1..4 LOOP
      part1 := part1 || substr(chars, floor(random() * length(chars) + 1)::int, 1);
      part2 := part2 || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    END LOOP;
    code := 'PDZ-' || part1 || '-' || part2;
    SELECT COUNT(*) INTO cnt FROM public.inventory_units WHERE public_claim_code = code;
    EXIT WHEN cnt = 0;
  END LOOP;
  RETURN code;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."generate_order_number"() RETURNS "text"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  num TEXT;
  cnt INTEGER;
BEGIN
  LOOP
    num := 'ORD-' || to_char(now(), 'YYMMDD') || '-' || upper(substr(md5(random()::text), 1, 5));
    SELECT COUNT(*) INTO cnt FROM public.orders WHERE order_number = num;
    EXIT WHEN cnt = 0;
  END LOOP;
  RETURN num;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."generate_tracking_code"() RETURNS "text"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
    code TEXT;
    exists_count INTEGER;
BEGIN
    LOOP
        code := 'PL-' || upper(substr(md5(random()::text), 1, 8));
        SELECT COUNT(*) INTO exists_count FROM public.postcards WHERE tracking_code = code;
        EXIT WHEN exists_count = 0;
    END LOOP;
    RETURN code;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  INSERT INTO public.profiles (user_id, display_name, first_name, last_name)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'display_name', NEW.email),
    NEW.raw_user_meta_data->>'first_name',
    NEW.raw_user_meta_data->>'last_name'
  );

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'traveler');

  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."has_role"("_user_id" "uuid", "_role" "public"."app_role") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = _role
  )
$$;




CREATE OR REPLACE FUNCTION "public"."is_valid_nip"("_nip" "text") RETURNS boolean
    LANGUAGE "plpgsql" IMMUTABLE
    AS $$
DECLARE
  _clean text;
  _weights integer[] := ARRAY[6, 5, 7, 2, 3, 4, 5, 6, 7];
  _sum integer := 0;
  _checksum integer;
  _i integer;
BEGIN
  IF _nip IS NULL THEN
    RETURN false;
  END IF;

  -- Remove all non-digit characters
  _clean := regexp_replace(_nip, '[^0-9]', '', 'g');

  -- NIP must be exactly 10 digits
  IF length(_clean) <> 10 THEN
    RETURN false;
  END IF;

  -- Calculate weighted sum for first 9 digits
  FOR _i IN 1..9 LOOP
    _sum := _sum + (substring(_clean from _i for 1)::integer * _weights[_i]);
  END LOOP;

  _checksum := _sum % 11;

  -- Modulo 11 must not equal 10, and must match the 10th digit
  IF _checksum = 10 THEN
    RETURN false;
  END IF;

  RETURN _checksum = substring(_clean from 10 for 1)::integer;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."log_inventory_unit_event"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _event_type inventory_event_type;
  _actor_type event_actor_type := 'system';
  _actor_id UUID;
  _payload JSONB := '{}'::jsonb;
BEGIN
  -- INSERT = created
  IF TG_OP = 'INSERT' THEN
    _event_type := 'created_in_stock';
    _payload := jsonb_build_object(
      'stock_batch_id', NEW.stock_batch_id,
      'card_design_id', NEW.card_design_id,
      'internal_inventory_code', NEW.internal_inventory_code
    );

    INSERT INTO public.inventory_unit_events (inventory_unit_id, event_type, actor_type, actor_id, payload_json)
    VALUES (NEW.id, _event_type, _actor_type, _actor_id, _payload);

    RETURN NEW;
  END IF;

  -- UPDATE: detect what changed
  IF TG_OP = 'UPDATE' THEN
    -- Reserved
    IF OLD.fulfillment_status = 'in_stock' AND NEW.fulfillment_status = 'reserved' THEN
      INSERT INTO public.inventory_unit_events (inventory_unit_id, event_type, actor_type, payload_json)
      VALUES (NEW.id, 'reserved_for_order', 'system', jsonb_build_object(
        'order_id', NEW.order_id,
        'traveler_user_id', NEW.traveler_user_id
      ));
    END IF;

    -- QR generated
    IF OLD.fulfillment_status IN ('in_stock', 'reserved') AND NEW.fulfillment_status = 'qr_generated' THEN
      INSERT INTO public.inventory_unit_events (inventory_unit_id, event_type, actor_type, payload_json)
      VALUES (NEW.id, 'qr_generated', 'admin', jsonb_build_object(
        'public_claim_code', NEW.public_claim_code
      ));
    END IF;

    -- QR applied
    IF OLD.fulfillment_status != 'qr_applied' AND NEW.fulfillment_status = 'qr_applied' THEN
      INSERT INTO public.inventory_unit_events (inventory_unit_id, event_type, actor_type, payload_json)
      VALUES (NEW.id, 'qr_applied', 'admin', '{}'::jsonb);
    END IF;

    -- Shipped
    IF OLD.fulfillment_status != 'shipped' AND NEW.fulfillment_status = 'shipped' THEN
      INSERT INTO public.inventory_unit_events (inventory_unit_id, event_type, actor_type, payload_json)
      VALUES (NEW.id, 'shipped', 'system', jsonb_build_object(
        'shipment_id', NEW.shipment_id
      ));
    END IF;

    -- Registered (business_status change)
    IF (OLD.business_status IS DISTINCT FROM 'registered') AND NEW.business_status = 'registered' THEN
      INSERT INTO public.inventory_unit_events (inventory_unit_id, event_type, actor_type, payload_json)
      VALUES (NEW.id, 'registered', 'recipient', '{}'::jsonb);
    END IF;

    -- Voided
    IF OLD.fulfillment_status != 'voided' AND NEW.fulfillment_status = 'voided' THEN
      INSERT INTO public.inventory_unit_events (inventory_unit_id, event_type, actor_type, payload_json)
      VALUES (NEW.id, 'voided', 'admin', jsonb_build_object(
        'previous_status', OLD.fulfillment_status
      ));
    END IF;

    -- Damaged
    IF OLD.fulfillment_status != 'damaged' AND NEW.fulfillment_status = 'damaged' THEN
      INSERT INTO public.inventory_unit_events (inventory_unit_id, event_type, actor_type, payload_json)
      VALUES (NEW.id, 'damaged', 'admin', jsonb_build_object(
        'previous_status', OLD.fulfillment_status
      ));
    END IF;

    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."notify_on_new_registration"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _traveler_id uuid;
BEGIN
  SELECT traveler_user_id INTO _traveler_id
  FROM public.inventory_units
  WHERE id = NEW.inventory_unit_id;

  IF _traveler_id IS NOT NULL THEN
    INSERT INTO public.notifications (user_id, title, message, type)
    VALUES (
      _traveler_id,
      'Nowa relacja!',
      'KtoĹ› wĹ‚aĹ›nie zarejestrowaĹ‚ TwojÄ… PodrĂłĹĽĂłwkÄ™. Zdobywasz punkty WpĹ‚ywu Kulturowego!',
      'new_registration'
    );
  END IF;
  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."notify_on_rank_change"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF OLD.current_rank IS DISTINCT FROM NEW.current_rank AND NEW.current_rank != 'Zwiadowca' THEN
    INSERT INTO public.notifications (user_id, title, message, type)
    VALUES (
      NEW.user_id,
      'AwansowaĹ‚eĹ›!',
      'Gratulacje, Twoja nowa ranga to ' || NEW.current_rank || '!',
      'rank_up'
    );
  END IF;
  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."on_inventory_unit_recalc_gamification"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF NEW.traveler_user_id IS NOT NULL THEN
    PERFORM public.calculate_user_impact_points(NEW.traveler_user_id);
  END IF;
  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."on_registration_add_kilometers"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _traveler_id uuid;
  _dist integer;
BEGIN
  IF NEW.latitude IS NULL OR NEW.longitude IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT traveler_user_id INTO _traveler_id
  FROM public.inventory_units
  WHERE id = NEW.inventory_unit_id;

  IF _traveler_id IS NULL THEN
    RETURN NEW;
  END IF;

  _dist := public.calculate_distance(52.2297, 21.0122, NEW.latitude, NEW.longitude)::integer;

  UPDATE public.profiles
  SET total_kilometers = total_kilometers + _dist
  WHERE user_id = _traveler_id;

  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."on_registration_recalc_gamification"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _traveler_id uuid;
BEGIN
  SELECT traveler_user_id INTO _traveler_id
  FROM public.inventory_units
  WHERE id = NEW.inventory_unit_id;

  IF _traveler_id IS NOT NULL THEN
    PERFORM public.calculate_user_impact_points(_traveler_id);
  END IF;

  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."on_shipment_shipped"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF NEW.status = 'shipped' AND (OLD.status IS DISTINCT FROM 'shipped') THEN
    -- Update shipped_at on shipment
    NEW.shipped_at := COALESCE(NEW.shipped_at, now());

    -- Update all inventory_units linked to this order
    UPDATE public.inventory_units
    SET fulfillment_status = 'shipped',
        shipped_at = now(),
        shipment_id = NEW.id::text
    WHERE order_id = NEW.order_id::text
      AND fulfillment_status IN ('reserved', 'qr_generated', 'qr_applied');
  END IF;

  IF NEW.status = 'delivered' AND (OLD.status IS DISTINCT FROM 'delivered') THEN
    NEW.delivered_at := COALESCE(NEW.delivered_at, now());
  END IF;

  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."prepare_pod_order"("_order_id" "uuid") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _order public.orders%ROWTYPE;
  _item record;
  _job_id uuid;
  _batch_id uuid;
  _unit_id uuid;
  _claim_code text;
  _token text;
  _item_no integer := 0;
  _copy_no integer;
BEGIN
  SELECT * INTO _order
  FROM public.orders
  WHERE id = _order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'order_not_found';
  END IF;

  IF _order.payment_status <> 'paid' THEN
    RAISE EXCEPTION 'order_not_paid';
  END IF;

  -- Idempotency protects against duplicate payment callbacks.
  SELECT id INTO _job_id
  FROM public.qr_print_jobs
  WHERE order_id = _order_id
  ORDER BY created_at DESC
  LIMIT 1;

  IF _job_id IS NOT NULL THEN
    RETURN _job_id;
  END IF;

  INSERT INTO public.qr_print_jobs (
    name, order_id, status, total_items, generated_items, created_by
  )
  VALUES (
    'POD â€” zamĂłwienie ' || _order.order_number,
    _order_id,
    'generating',
    0,
    0,
    _order.user_id
  )
  RETURNING id INTO _job_id;

  FOR _item IN
    SELECT id, card_design_id, quantity
    FROM public.order_items
    WHERE order_id = _order_id
    ORDER BY created_at, id
  LOOP
    -- A batch records the print run for traceability; it is not store stock.
    INSERT INTO public.stock_batches (name, description, card_design_id, quantity)
    VALUES (
      'POD ' || _order.order_number,
      'Sztuki utworzone automatycznie po opĹ‚aceniu zamĂłwienia.',
      _item.card_design_id,
      _item.quantity
    )
    RETURNING id INTO _batch_id;

    FOR _copy_no IN 1.._item.quantity LOOP
      _item_no := _item_no + 1;
      _claim_code := public.generate_claim_code();
      -- md5 over random value, time and order id is sufficient for the public
      -- registration token and does not require the pgcrypto extension.
      _token := md5(random()::text || clock_timestamp()::text || _order_id::text);

      INSERT INTO public.inventory_units (
        stock_batch_id,
        card_design_id,
        internal_inventory_code,
        business_status,
        fulfillment_status,
        traveler_user_id,
        order_id,
        order_item_id,
        public_claim_code,
        public_claim_token_hash,
        qr_generated_at
      )
      VALUES (
        _batch_id,
        _item.card_design_id,
        'POD-' || upper(substr(replace(_order_id::text, '-', ''), 1, 8)) || '-' || lpad(_item_no::text, 3, '0'),
        'purchased',
        'qr_generated',
        _order.user_id,
        _order_id::text,
        _item.id::text,
        _claim_code,
        -- This column also accepts legacy SHA-256 hashes. POD tokens are stored
        -- as an unguessable 32-character value because this database does not
        -- expose a server-side SHA-256 helper.
        _token,
        now()
      )
      RETURNING id INTO _unit_id;

      INSERT INTO public.qr_print_job_items (
        print_job_id, inventory_unit_id, public_claim_code, qr_url
      )
      VALUES (
        _job_id,
        _unit_id,
        _claim_code,
        '/r/' || _token
      );
    END LOOP;
  END LOOP;

  IF _item_no = 0 THEN
    RAISE EXCEPTION 'order_has_no_items';
  END IF;

  UPDATE public.qr_print_jobs
  SET status = 'ready', total_items = _item_no, generated_items = _item_no
  WHERE id = _job_id;

  RETURN _job_id;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."prepare_pod_order_after_payment"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF NEW.payment_status = 'paid'
     AND (TG_OP = 'INSERT' OR OLD.payment_status IS DISTINCT FROM 'paid') THEN
    PERFORM public.prepare_pod_order(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."recalculate_user_gamification"("_user_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _unit_count int;
  _unique_countries int;
  _reg_count int;
  _total int;
  _rank text;
BEGIN
  SELECT
    COUNT(*)::int,
    COUNT(DISTINCT cd.country_id)::int
  INTO _unit_count, _unique_countries
  FROM public.inventory_units iu
  JOIN public.card_designs cd ON cd.id = iu.card_design_id
  WHERE iu.traveler_user_id = _user_id;

  SELECT COUNT(*)::int INTO _reg_count
  FROM public.recipient_registrations rr
  JOIN public.inventory_units iu ON iu.id = rr.inventory_unit_id
  WHERE iu.traveler_user_id = _user_id;

  _total := (_unit_count * 10) + (_unique_countries * 50) + (_reg_count * 100);

  _rank := CASE
    WHEN _total >= 7500 THEN 'Legenda PodrĂłĹĽĂłwki'
    WHEN _total >= 2500 THEN 'Misjonarz Kultury'
    WHEN _total >= 500 THEN 'Ambasador'
    ELSE 'Zwiadowca'
  END;

  UPDATE public.profiles
  SET total_points = _total,
      current_rank = _rank
  WHERE user_id = _user_id;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."register_recipient"("_unit_id" "uuid", "_recipient_name" "text", "_recipient_message" "text", "_recipient_email" "text", "_contact_opt_in" boolean, "_latitude" numeric, "_longitude" numeric) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _status text;
BEGIN
  SELECT business_status INTO _status
  FROM public.inventory_units
  WHERE id = _unit_id
  FOR UPDATE;

  IF _status IS NULL THEN
    RAISE EXCEPTION 'not_found';
  END IF;
  IF _status = 'registered' THEN
    RAISE EXCEPTION 'already_registered';
  END IF;
  IF _status <> 'purchased' THEN
    RAISE EXCEPTION 'not_activated';
  END IF;

  INSERT INTO public.recipient_registrations(
    inventory_unit_id, recipient_name, recipient_message, recipient_email,
    contact_opt_in, latitude, longitude
  ) VALUES (
    _unit_id, _recipient_name, _recipient_message, _recipient_email,
    _contact_opt_in, _latitude, _longitude
  );

  UPDATE public.inventory_units
  SET business_status = 'registered', registered_at = now()
  WHERE id = _unit_id;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."register_recipient"("_unit_id" "uuid", "_recipient_name" "text", "_recipient_message" "text", "_recipient_email" "text", "_contact_opt_in" boolean, "_latitude" numeric, "_longitude" numeric, "_registered_country_iso2" "text" DEFAULT NULL::"text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _status text;
BEGIN
  SELECT business_status INTO _status
  FROM public.inventory_units
  WHERE id = _unit_id
  FOR UPDATE;

  IF _status IS NULL THEN
    RAISE EXCEPTION 'not_found';
  END IF;

  IF _status = 'registered' THEN
    RAISE EXCEPTION 'already_registered';
  END IF;

  IF _status <> 'purchased' THEN
    RAISE EXCEPTION 'not_activated';
  END IF;

  INSERT INTO public.recipient_registrations(
    inventory_unit_id, recipient_name, recipient_message, recipient_email,
    contact_opt_in, latitude, longitude, registered_country_iso2
  ) VALUES (
    _unit_id, _recipient_name, _recipient_message, _recipient_email,
    _contact_opt_in, _latitude, _longitude, _registered_country_iso2
  );

  UPDATE public.inventory_units
  SET business_status = 'registered', registered_at = now()
  WHERE id = _unit_id;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."reserve_inventory_for_order"("_order_id" "uuid") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  _order RECORD;
  _item RECORD;
  _reserved_count INTEGER;
  _available_count INTEGER;
  _unit_ids UUID[];
  _result JSONB := '{"reserved": []}'::jsonb;
  _errors JSONB := '[]'::jsonb;
BEGIN
  -- Admin-only check
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN jsonb_build_object('success', false, 'error', 'Admin access required');
  END IF;

  SELECT * INTO _order FROM public.orders WHERE id = _order_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'ZamĂłwienie nie istnieje');
  END IF;

  IF _order.payment_status != 'paid' THEN
    RETURN jsonb_build_object('success', false, 'error', 'ZamĂłwienie nie jest opĹ‚acone');
  END IF;

  SELECT COUNT(*) INTO _reserved_count
  FROM public.inventory_units
  WHERE order_id = _order_id::text;

  IF _reserved_count > 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'ZamĂłwienie ma juĹĽ zarezerwowane sztuki (' || _reserved_count || ')');
  END IF;

  FOR _item IN
    SELECT oi.id AS item_id, oi.card_design_id, oi.quantity
    FROM public.order_items oi
    WHERE oi.order_id = _order_id
  LOOP
    SELECT COUNT(*) INTO _available_count
    FROM public.inventory_units
    WHERE card_design_id = _item.card_design_id
      AND fulfillment_status = 'in_stock'
      AND order_id IS NULL;

    IF _available_count < _item.quantity THEN
      _errors := _errors || jsonb_build_array(jsonb_build_object(
        'card_design_id', _item.card_design_id,
        'requested', _item.quantity,
        'available', _available_count
      ));
    END IF;
  END LOOP;

  IF jsonb_array_length(_errors) > 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Brak wystarczajÄ…cej iloĹ›ci sztuk w magazynie',
      'shortages', _errors
    );
  END IF;

  FOR _item IN
    SELECT oi.id AS item_id, oi.card_design_id, oi.quantity
    FROM public.order_items oi
    WHERE oi.order_id = _order_id
  LOOP
    SELECT ARRAY_AGG(id) INTO _unit_ids
    FROM (
      SELECT id
      FROM public.inventory_units
      WHERE card_design_id = _item.card_design_id
        AND fulfillment_status = 'in_stock'
        AND order_id IS NULL
      ORDER BY created_at ASC
      LIMIT _item.quantity
      FOR UPDATE SKIP LOCKED
    ) sub;

    UPDATE public.inventory_units
    SET fulfillment_status = 'reserved',
        business_status = 'purchased',
        traveler_user_id = _order.user_id,
        order_id = _order_id::text,
        order_item_id = _item.item_id::text
    WHERE id = ANY(_unit_ids);

    _result := jsonb_set(_result, '{reserved}',
      (_result->'reserved') || jsonb_build_array(jsonb_build_object(
        'order_item_id', _item.item_id,
        'card_design_id', _item.card_design_id,
        'count', array_length(_unit_ids, 1)
      ))
    );
  END LOOP;

  RETURN jsonb_build_object('success', true, 'details', _result);
END;
$$;




CREATE OR REPLACE FUNCTION "public"."update_country_count"() RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  UPDATE public.platform_stats
  SET total_countries = (
    SELECT COUNT(DISTINCT c.id)
    FROM public.postcards p
    JOIN public.designs d ON p.design_id = d.id
    JOIN public.countries c ON d.country_id = c.id
    WHERE p.status IN ('purchased', 'registered')
  );
END;
$$;




CREATE OR REPLACE FUNCTION "public"."update_member_count"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
    UPDATE public.platform_stats
    SET total_members = (SELECT COUNT(*) FROM public.profiles);
    RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."update_platform_stats_on_postcard"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
    -- Update total_purchased on insert
    IF TG_OP = 'INSERT' THEN
        UPDATE public.platform_stats
        SET total_purchased = total_purchased + 1;
    END IF;

    -- Update total_given when status changes to delivered
    IF TG_OP = 'UPDATE' AND OLD.status != 'delivered' AND NEW.status = 'delivered' THEN
        UPDATE public.platform_stats
        SET total_given = total_given + 1;

        -- Update country count if new country
        IF NEW.given_to_country IS NOT NULL THEN
            UPDATE public.platform_stats
            SET total_countries = (
                SELECT COUNT(DISTINCT given_to_country)
                FROM public.postcards
                WHERE status = 'delivered' AND given_to_country IS NOT NULL
            );
        END IF;
    END IF;

    RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."update_platform_stats_on_postcard_v2"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  -- On purchase
  IF TG_OP = 'UPDATE' AND OLD.status = 'available' AND NEW.status = 'purchased' THEN
    UPDATE public.platform_stats
    SET total_purchased = total_purchased + 1;
  END IF;

  -- On registration
  IF TG_OP = 'UPDATE' AND OLD.status = 'purchased' AND NEW.status = 'registered' THEN
    UPDATE public.platform_stats
    SET total_registered = total_registered + 1;
  END IF;

  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."update_profile_stats_on_postcard"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
    -- Update giver stats when postcard is delivered
    IF TG_OP = 'UPDATE' AND OLD.status != 'delivered' AND NEW.status = 'delivered' THEN
        UPDATE public.profiles
        SET postcards_given = postcards_given + 1
        WHERE user_id = NEW.owner_id;

        -- Update receiver stats if receiver exists
        IF NEW.receiver_id IS NOT NULL THEN
            UPDATE public.profiles
            SET postcards_received = postcards_received + 1
            WHERE user_id = NEW.receiver_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."update_profile_stats_on_postcard_v2"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.status = 'available' AND NEW.status = 'purchased' AND NEW.buyer_id IS NOT NULL THEN
    UPDATE public.profiles
    SET postcards_purchased = postcards_purchased + 1
    WHERE user_id = NEW.buyer_id;
  END IF;

  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."validate_postcard_status"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF NEW.status NOT IN ('available', 'purchased', 'registered') THEN
    RAISE EXCEPTION 'Invalid postcard status: %', NEW.status;
  END IF;
  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."validate_profile_input"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF length(NEW.display_name) > 100 THEN
    RAISE EXCEPTION 'display_name too long (max 100)';
  END IF;
  IF length(NEW.first_name) > 50 THEN
    RAISE EXCEPTION 'first_name too long (max 50)';
  END IF;
  IF length(NEW.last_name) > 50 THEN
    RAISE EXCEPTION 'last_name too long (max 50)';
  END IF;
  IF length(NEW.bio) > 1000 THEN
    RAISE EXCEPTION 'bio too long (max 1000)';
  END IF;
  IF length(NEW.city) > 100 THEN
    RAISE EXCEPTION 'city too long (max 100)';
  END IF;
  IF length(NEW.country) > 100 THEN
    RAISE EXCEPTION 'country too long (max 100)';
  END IF;
  IF length(NEW.avatar_url) > 500 THEN
    RAISE EXCEPTION 'avatar_url too long (max 500)';
  END IF;
  RETURN NEW;
END;
$$;




CREATE OR REPLACE FUNCTION "public"."validate_registration_input"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF length(NEW.recipient_name) > 100 THEN
    RAISE EXCEPTION 'recipient_name too long (max 100)';
  END IF;
  IF length(NEW.recipient_message) > 500 THEN
    RAISE EXCEPTION 'recipient_message too long (max 500)';
  END IF;
  IF length(NEW.recipient_email) > 255 THEN
    RAISE EXCEPTION 'recipient_email too long (max 255)';
  END IF;
  RETURN NEW;
END;
$$;




CREATE TABLE IF NOT EXISTS "public"."card_design_images" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "card_design_id" "uuid" NOT NULL,
    "url" "text" NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."card_designs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "country_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "language_code" "text" DEFAULT 'en'::"text" NOT NULL,
    "view_no" integer NOT NULL,
    "title" "text",
    "thank_you_text" "text",
    "image_front_url" "text",
    "active" boolean DEFAULT true NOT NULL,
    "category_id" "uuid",
    "price_grosze" integer DEFAULT 0 NOT NULL,
    "currency" "text" DEFAULT 'PLN'::"text" NOT NULL,
    "description" "text",
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "photo_author" "text",
    "crop_settings" "jsonb" DEFAULT '{"x": 50, "y": 50, "fit": "auto", "zoom": 100}'::"jsonb",
    "back_qr_label" "text"
);




CREATE TABLE IF NOT EXISTS "public"."card_language_templates" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "country_id" "uuid" NOT NULL,
    "language_code" "text" NOT NULL,
    "language_name" "text" NOT NULL,
    "front_thank_you_text" "text" NOT NULL,
    "back_qr_label" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "icon_url" "text",
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."countries" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name_pl" "text" NOT NULL,
    "iso2" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "iso3" "text",
    "slug" "text",
    "active" boolean DEFAULT true NOT NULL,
    "flag_url" "text"
);




CREATE TABLE IF NOT EXISTS "public"."feature_flags" (
    "key" "text" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "is_enabled" boolean DEFAULT false NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."gamification_config" (
    "id" integer DEFAULT 1 NOT NULL,
    "points_per_unit" integer DEFAULT 10 NOT NULL,
    "points_per_country" integer DEFAULT 50 NOT NULL,
    "points_per_registration" integer DEFAULT 100 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "singleton_id" CHECK (("id" = 1))
);




CREATE TABLE IF NOT EXISTS "public"."gamification_tiers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "min_points" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."inventory_unit_events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "inventory_unit_id" "uuid" NOT NULL,
    "event_type" "public"."inventory_event_type" NOT NULL,
    "actor_type" "public"."event_actor_type" DEFAULT 'system'::"public"."event_actor_type" NOT NULL,
    "actor_id" "uuid",
    "payload_json" "jsonb" DEFAULT '{}'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."inventory_units" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "stock_batch_id" "uuid" NOT NULL,
    "card_design_id" "uuid" NOT NULL,
    "internal_inventory_code" "text" NOT NULL,
    "business_status" "public"."business_status",
    "fulfillment_status" "public"."fulfillment_status" DEFAULT 'in_stock'::"public"."fulfillment_status" NOT NULL,
    "traveler_user_id" "uuid",
    "order_id" "text",
    "order_item_id" "text",
    "shipment_id" "text",
    "public_claim_code" "text",
    "public_claim_token_hash" "text",
    "qr_generated_at" timestamp with time zone,
    "qr_applied_at" timestamp with time zone,
    "shipped_at" timestamp with time zone,
    "registered_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "message" "text" NOT NULL,
    "type" "text" DEFAULT 'info'::"text" NOT NULL,
    "is_read" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."order_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "order_id" "uuid" NOT NULL,
    "card_design_id" "uuid" NOT NULL,
    "quantity" integer DEFAULT 1 NOT NULL,
    "unit_price" numeric(10,2) DEFAULT 0 NOT NULL,
    "total_price" numeric(10,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "order_number" "text" DEFAULT "public"."generate_order_number"() NOT NULL,
    "status" "public"."order_status" DEFAULT 'pending'::"public"."order_status" NOT NULL,
    "payment_status" "public"."payment_status" DEFAULT 'unpaid'::"public"."payment_status" NOT NULL,
    "total_amount" numeric(10,2) DEFAULT 0 NOT NULL,
    "currency" "text" DEFAULT 'PLN'::"text" NOT NULL,
    "shipping_name" "text",
    "shipping_address" "text",
    "shipping_city" "text",
    "shipping_postal_code" "text",
    "shipping_country" "text",
    "notes" "text",
    "paid_at" timestamp with time zone,
    "fulfilled_at" timestamp with time zone,
    "cancelled_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pickup_point_name" "text",
    "pickup_point_address" "text",
    "pickup_point_city" "text",
    "shipping_cost" numeric(10,2),
    "invoice_requested" boolean DEFAULT false NOT NULL,
    "company_name" "text",
    "company_nip" "text",
    "company_address" "text",
    "payment_method" "text" DEFAULT 'online'::"text" NOT NULL,
    "shipping_method" "text" DEFAULT 'inpost'::"text" NOT NULL,
    "shipping_phone" "text",
    "fiscal_document_status" "text",
    "fiscal_document_number" "text",
    "fiscal_document_error" "text",
    "fiscal_document_external_id" "text",
    "fiscal_document_issued_at" timestamp with time zone,
    "fiscal_document_url" "text",
    "customer_email" "text",
    CONSTRAINT "orders_payment_method_check" CHECK (("payment_method" = ANY (ARRAY['online'::"text", 'cod'::"text"]))),
    CONSTRAINT "orders_shipping_method_check" CHECK (("shipping_method" = ANY (ARRAY['inpost'::"text", 'courier'::"text"])))
);




CREATE TABLE IF NOT EXISTS "public"."platform_stats" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "total_members" integer DEFAULT 0 NOT NULL,
    "total_countries" integer DEFAULT 0 NOT NULL,
    "total_given" integer DEFAULT 0 NOT NULL,
    "total_purchased" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "total_registered" integer DEFAULT 0 NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."postcards" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "design_id" "uuid" NOT NULL,
    "serial_number" integer NOT NULL,
    "qr_token" "text" NOT NULL,
    "status" "text" DEFAULT 'available'::"text" NOT NULL,
    "buyer_id" "uuid",
    "buyer_display_name" "text",
    "purchased_at" timestamp with time zone,
    "order_reference" "text",
    "recipient_name" "text",
    "recipient_message" "text",
    "recipient_email" "text",
    "registered_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "display_name" "text",
    "avatar_url" "text",
    "country" "text",
    "city" "text",
    "bio" "text",
    "postcards_purchased" integer DEFAULT 0 NOT NULL,
    "postcards_received" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "total_points" integer DEFAULT 0 NOT NULL,
    "current_rank" "text" DEFAULT 'Zwiadowca'::"text" NOT NULL,
    "total_kilometers" integer DEFAULT 0 NOT NULL
);




CREATE OR REPLACE VIEW "public"."profiles_public" WITH ("security_invoker"='true') AS
 SELECT "id",
    "user_id",
    "display_name",
    "avatar_url",
    "total_points",
    "current_rank",
    "total_kilometers",
    "postcards_purchased",
    "postcards_received"
   FROM "public"."profiles";




CREATE TABLE IF NOT EXISTS "public"."qr_print_job_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "print_job_id" "uuid" NOT NULL,
    "inventory_unit_id" "uuid" NOT NULL,
    "public_claim_code" "text" NOT NULL,
    "qr_url" "text" NOT NULL,
    "generated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."qr_print_jobs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "shipment_id" "text",
    "order_id" "uuid",
    "status" "public"."qr_print_job_status" DEFAULT 'pending'::"public"."qr_print_job_status" NOT NULL,
    "total_items" integer DEFAULT 0 NOT NULL,
    "generated_items" integer DEFAULT 0 NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);




CREATE TABLE IF NOT EXISTS "public"."shipments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "order_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "status" "public"."shipment_status" DEFAULT 'pending'::"public"."shipment_status" NOT NULL,
    "tracking_number" "text",
    "carrier" "text",
    "shipping_method" "text",
    "shipped_at" timestamp with time zone,
    "delivered_at" timestamp with time zone,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "inpost_shipment_id" "text",
    "label_url" "text",
    "size" "text"
);




CREATE TABLE IF NOT EXISTS "public"."stock_batches" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "card_design_id" "uuid" NOT NULL,
    "quantity" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);




CREATE OR REPLACE VIEW "public"."traveler_registrations_view" WITH ("security_invoker"='true') AS
 SELECT "id",
    "inventory_unit_id",
    "recipient_name",
    "recipient_message",
        CASE
            WHEN "contact_opt_in" THEN "recipient_email"
            ELSE NULL::"text"
        END AS "recipient_email",
    "contact_opt_in",
    "registered_at",
    "created_at"
   FROM "public"."recipient_registrations" "rr"
  WHERE (EXISTS ( SELECT 1
           FROM "public"."inventory_units" "iu"
          WHERE (("iu"."id" = "rr"."inventory_unit_id") AND ("iu"."traveler_user_id" = "auth"."uid"()))));




CREATE OR REPLACE VIEW "public"."user_gamification_stats" WITH ("security_invoker"='true') AS
 SELECT "p"."user_id",
    "p"."display_name",
    COALESCE("unit_stats"."unit_count", 0) AS "unit_count",
    COALESCE("unit_stats"."unique_countries", 0) AS "unique_countries",
    COALESCE("reg_stats"."registration_count", 0) AS "registration_count",
    (((COALESCE("unit_stats"."unit_count", 0) * 10) + (COALESCE("unit_stats"."unique_countries", 0) * 50)) + (COALESCE("reg_stats"."registration_count", 0) * 100)) AS "total_points",
        CASE
            WHEN ((((COALESCE("unit_stats"."unit_count", 0) * 10) + (COALESCE("unit_stats"."unique_countries", 0) * 50)) + (COALESCE("reg_stats"."registration_count", 0) * 100)) >= 7500) THEN 'Legenda PodrĂłĹĽĂłwki'::"text"
            WHEN ((((COALESCE("unit_stats"."unit_count", 0) * 10) + (COALESCE("unit_stats"."unique_countries", 0) * 50)) + (COALESCE("reg_stats"."registration_count", 0) * 100)) >= 2500) THEN 'Misjonarz Kultury'::"text"
            WHEN ((((COALESCE("unit_stats"."unit_count", 0) * 10) + (COALESCE("unit_stats"."unique_countries", 0) * 50)) + (COALESCE("reg_stats"."registration_count", 0) * 100)) >= 500) THEN 'Ambasador'::"text"
            ELSE 'Zwiadowca'::"text"
        END AS "impact_rank"
   FROM (("public"."profiles" "p"
     LEFT JOIN LATERAL ( SELECT ("count"(*))::integer AS "unit_count",
            ("count"(DISTINCT "cd"."country_id"))::integer AS "unique_countries"
           FROM ("public"."inventory_units" "iu"
             JOIN "public"."card_designs" "cd" ON (("cd"."id" = "iu"."card_design_id")))
          WHERE ("iu"."traveler_user_id" = "p"."user_id")) "unit_stats" ON (true))
     LEFT JOIN LATERAL ( SELECT ("count"(*))::integer AS "registration_count"
           FROM ("public"."recipient_registrations" "rr"
             JOIN "public"."inventory_units" "iu" ON (("iu"."id" = "rr"."inventory_unit_id")))
          WHERE ("iu"."traveler_user_id" = "p"."user_id")) "reg_stats" ON (true));




CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "role" "public"."app_role" NOT NULL
);




ALTER TABLE ONLY "public"."card_design_images"
    ADD CONSTRAINT "card_design_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."card_designs"
    ADD CONSTRAINT "card_designs_country_category_view_uniq" UNIQUE ("country_id", "category_id", "view_no");



ALTER TABLE ONLY "public"."card_language_templates"
    ADD CONSTRAINT "card_language_templates_country_lang_key" UNIQUE ("country_id", "language_code");



ALTER TABLE ONLY "public"."card_language_templates"
    ADD CONSTRAINT "card_language_templates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_code_key" UNIQUE ("iso2");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_name_key" UNIQUE ("name_pl");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_slug_unique" UNIQUE ("slug");



ALTER TABLE ONLY "public"."card_designs"
    ADD CONSTRAINT "designs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feature_flags"
    ADD CONSTRAINT "feature_flags_pkey" PRIMARY KEY ("key");



ALTER TABLE ONLY "public"."gamification_config"
    ADD CONSTRAINT "gamification_config_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."gamification_tiers"
    ADD CONSTRAINT "gamification_tiers_min_points_key" UNIQUE ("min_points");



ALTER TABLE ONLY "public"."gamification_tiers"
    ADD CONSTRAINT "gamification_tiers_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."gamification_tiers"
    ADD CONSTRAINT "gamification_tiers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventory_unit_events"
    ADD CONSTRAINT "inventory_unit_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventory_units"
    ADD CONSTRAINT "inventory_units_internal_inventory_code_key" UNIQUE ("internal_inventory_code");



ALTER TABLE ONLY "public"."inventory_units"
    ADD CONSTRAINT "inventory_units_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventory_units"
    ADD CONSTRAINT "inventory_units_public_claim_code_key" UNIQUE ("public_claim_code");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_order_number_key" UNIQUE ("order_number");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."platform_stats"
    ADD CONSTRAINT "platform_stats_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."postcards"
    ADD CONSTRAINT "postcards_design_id_serial_number_key" UNIQUE ("design_id", "serial_number");



ALTER TABLE ONLY "public"."postcards"
    ADD CONSTRAINT "postcards_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."postcards"
    ADD CONSTRAINT "postcards_qr_token_key" UNIQUE ("qr_token");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."qr_print_job_items"
    ADD CONSTRAINT "qr_print_job_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."qr_print_job_items"
    ADD CONSTRAINT "qr_print_job_items_print_job_id_inventory_unit_id_key" UNIQUE ("print_job_id", "inventory_unit_id");



ALTER TABLE ONLY "public"."qr_print_jobs"
    ADD CONSTRAINT "qr_print_jobs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recipient_registrations"
    ADD CONSTRAINT "recipient_registrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."shipments"
    ADD CONSTRAINT "shipments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stock_batches"
    ADD CONSTRAINT "stock_batches_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recipient_registrations"
    ADD CONSTRAINT "uq_recipient_registrations_unit" UNIQUE ("inventory_unit_id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_user_id_role_key" UNIQUE ("user_id", "role");



CREATE INDEX "card_design_images_design_idx" ON "public"."card_design_images" USING "btree" ("card_design_id", "sort_order");



CREATE INDEX "idx_card_designs_category_id" ON "public"."card_designs" USING "btree" ("category_id");



CREATE INDEX "idx_inventory_unit_events_type" ON "public"."inventory_unit_events" USING "btree" ("event_type");



CREATE INDEX "idx_inventory_unit_events_unit" ON "public"."inventory_unit_events" USING "btree" ("inventory_unit_id");



CREATE INDEX "idx_inventory_units_batch" ON "public"."inventory_units" USING "btree" ("stock_batch_id");



CREATE INDEX "idx_inventory_units_business" ON "public"."inventory_units" USING "btree" ("business_status");



CREATE INDEX "idx_inventory_units_claim_code" ON "public"."inventory_units" USING "btree" ("public_claim_code");



CREATE INDEX "idx_inventory_units_design" ON "public"."inventory_units" USING "btree" ("card_design_id");



CREATE INDEX "idx_inventory_units_fulfillment" ON "public"."inventory_units" USING "btree" ("fulfillment_status");



CREATE INDEX "idx_notifications_user_id" ON "public"."notifications" USING "btree" ("user_id");



CREATE INDEX "idx_notifications_user_unread" ON "public"."notifications" USING "btree" ("user_id", "is_read") WHERE ("is_read" = false);



CREATE INDEX "idx_order_items_design" ON "public"."order_items" USING "btree" ("card_design_id");



CREATE INDEX "idx_order_items_order" ON "public"."order_items" USING "btree" ("order_id");



CREATE INDEX "idx_orders_payment" ON "public"."orders" USING "btree" ("payment_status");



CREATE INDEX "idx_orders_status" ON "public"."orders" USING "btree" ("status");



CREATE INDEX "idx_orders_user" ON "public"."orders" USING "btree" ("user_id");



CREATE INDEX "idx_qr_print_job_items_job" ON "public"."qr_print_job_items" USING "btree" ("print_job_id");



CREATE INDEX "idx_qr_print_job_items_unit" ON "public"."qr_print_job_items" USING "btree" ("inventory_unit_id");



CREATE INDEX "idx_qr_print_jobs_order" ON "public"."qr_print_jobs" USING "btree" ("order_id");



CREATE INDEX "idx_qr_print_jobs_status" ON "public"."qr_print_jobs" USING "btree" ("status");



CREATE INDEX "idx_recipient_registrations_country" ON "public"."recipient_registrations" USING "btree" ("registered_country_iso2");



CREATE INDEX "idx_shipments_order" ON "public"."shipments" USING "btree" ("order_id");



CREATE INDEX "idx_shipments_status" ON "public"."shipments" USING "btree" ("status");



CREATE INDEX "idx_shipments_user" ON "public"."shipments" USING "btree" ("user_id");



CREATE INDEX "idx_stock_batches_card_design_id" ON "public"."stock_batches" USING "btree" ("card_design_id");



CREATE OR REPLACE TRIGGER "prepare_pod_order_after_payment" AFTER INSERT OR UPDATE OF "payment_status" ON "public"."orders" FOR EACH ROW EXECUTE FUNCTION "public"."prepare_pod_order_after_payment"();



CREATE OR REPLACE TRIGGER "trg_card_language_templates_updated_at" BEFORE UPDATE ON "public"."card_language_templates" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "trg_inventory_unit_events" AFTER INSERT OR UPDATE ON "public"."inventory_units" FOR EACH ROW EXECUTE FUNCTION "public"."log_inventory_unit_event"();



CREATE OR REPLACE TRIGGER "trg_inventory_unit_gamification" AFTER INSERT ON "public"."inventory_units" FOR EACH ROW EXECUTE FUNCTION "public"."on_inventory_unit_recalc_gamification"();



CREATE OR REPLACE TRIGGER "trg_inventory_unit_recalc_gamification" AFTER INSERT OR UPDATE ON "public"."inventory_units" FOR EACH ROW EXECUTE FUNCTION "public"."on_inventory_unit_recalc_gamification"();



CREATE OR REPLACE TRIGGER "trg_inventory_units_updated_at" BEFORE UPDATE ON "public"."inventory_units" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "trg_log_inventory_unit_event" AFTER INSERT OR UPDATE ON "public"."inventory_units" FOR EACH ROW EXECUTE FUNCTION "public"."log_inventory_unit_event"();



CREATE OR REPLACE TRIGGER "trg_notify_new_registration" AFTER INSERT ON "public"."recipient_registrations" FOR EACH ROW EXECUTE FUNCTION "public"."notify_on_new_registration"();



CREATE OR REPLACE TRIGGER "trg_notify_on_new_registration" AFTER INSERT ON "public"."recipient_registrations" FOR EACH ROW EXECUTE FUNCTION "public"."notify_on_new_registration"();



CREATE OR REPLACE TRIGGER "trg_notify_on_rank_change" AFTER UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."notify_on_rank_change"();



CREATE OR REPLACE TRIGGER "trg_notify_rank_change" AFTER UPDATE OF "current_rank" ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."notify_on_rank_change"();



CREATE OR REPLACE TRIGGER "trg_on_shipment_shipped" BEFORE UPDATE ON "public"."shipments" FOR EACH ROW EXECUTE FUNCTION "public"."on_shipment_shipped"();



CREATE OR REPLACE TRIGGER "trg_orders_updated_at" BEFORE UPDATE ON "public"."orders" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "trg_profiles_updated_at" BEFORE UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "trg_registration_add_kilometers" AFTER INSERT ON "public"."recipient_registrations" FOR EACH ROW EXECUTE FUNCTION "public"."on_registration_add_kilometers"();



CREATE OR REPLACE TRIGGER "trg_registration_gamification" AFTER INSERT ON "public"."recipient_registrations" FOR EACH ROW EXECUTE FUNCTION "public"."on_registration_recalc_gamification"();



CREATE OR REPLACE TRIGGER "trg_registration_kilometers" AFTER INSERT ON "public"."recipient_registrations" FOR EACH ROW EXECUTE FUNCTION "public"."on_registration_add_kilometers"();



CREATE OR REPLACE TRIGGER "trg_registration_recalc_gamification" AFTER INSERT ON "public"."recipient_registrations" FOR EACH ROW EXECUTE FUNCTION "public"."on_registration_recalc_gamification"();



CREATE OR REPLACE TRIGGER "trg_shipment_shipped" BEFORE UPDATE ON "public"."shipments" FOR EACH ROW EXECUTE FUNCTION "public"."on_shipment_shipped"();



CREATE OR REPLACE TRIGGER "trg_update_member_count" AFTER INSERT ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."update_member_count"();



CREATE OR REPLACE TRIGGER "trg_validate_profile_input" BEFORE INSERT OR UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."validate_profile_input"();



CREATE OR REPLACE TRIGGER "trg_validate_registration_input" BEFORE INSERT OR UPDATE ON "public"."recipient_registrations" FOR EACH ROW EXECUTE FUNCTION "public"."validate_registration_input"();



CREATE OR REPLACE TRIGGER "update_inventory_units_updated_at" BEFORE UPDATE ON "public"."inventory_units" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_member_count_trigger" AFTER INSERT OR DELETE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."update_member_count"();



CREATE OR REPLACE TRIGGER "update_orders_updated_at" BEFORE UPDATE ON "public"."orders" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_platform_stats_trigger" AFTER UPDATE ON "public"."postcards" FOR EACH ROW EXECUTE FUNCTION "public"."update_platform_stats_on_postcard_v2"();



CREATE OR REPLACE TRIGGER "update_platform_stats_updated_at" BEFORE UPDATE ON "public"."platform_stats" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_postcards_updated_at" BEFORE UPDATE ON "public"."postcards" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_profile_stats_trigger" AFTER UPDATE ON "public"."postcards" FOR EACH ROW EXECUTE FUNCTION "public"."update_profile_stats_on_postcard_v2"();



CREATE OR REPLACE TRIGGER "update_profiles_updated_at" BEFORE UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_qr_print_jobs_updated_at" BEFORE UPDATE ON "public"."qr_print_jobs" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_shipments_updated_at" BEFORE UPDATE ON "public"."shipments" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_stock_batches_updated_at" BEFORE UPDATE ON "public"."stock_batches" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "validate_postcard_status_trigger" BEFORE INSERT OR UPDATE ON "public"."postcards" FOR EACH ROW EXECUTE FUNCTION "public"."validate_postcard_status"();



ALTER TABLE ONLY "public"."card_design_images"
    ADD CONSTRAINT "card_design_images_card_design_id_fkey" FOREIGN KEY ("card_design_id") REFERENCES "public"."card_designs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."card_designs"
    ADD CONSTRAINT "card_designs_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."card_language_templates"
    ADD CONSTRAINT "card_language_templates_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."card_designs"
    ADD CONSTRAINT "designs_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventory_unit_events"
    ADD CONSTRAINT "inventory_unit_events_inventory_unit_id_fkey" FOREIGN KEY ("inventory_unit_id") REFERENCES "public"."inventory_units"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventory_units"
    ADD CONSTRAINT "inventory_units_card_design_id_fkey" FOREIGN KEY ("card_design_id") REFERENCES "public"."card_designs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."inventory_units"
    ADD CONSTRAINT "inventory_units_stock_batch_id_fkey" FOREIGN KEY ("stock_batch_id") REFERENCES "public"."stock_batches"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_card_design_id_fkey" FOREIGN KEY ("card_design_id") REFERENCES "public"."card_designs"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."postcards"
    ADD CONSTRAINT "postcards_design_id_fkey" FOREIGN KEY ("design_id") REFERENCES "public"."card_designs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."qr_print_job_items"
    ADD CONSTRAINT "qr_print_job_items_inventory_unit_id_fkey" FOREIGN KEY ("inventory_unit_id") REFERENCES "public"."inventory_units"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."qr_print_job_items"
    ADD CONSTRAINT "qr_print_job_items_print_job_id_fkey" FOREIGN KEY ("print_job_id") REFERENCES "public"."qr_print_jobs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."qr_print_jobs"
    ADD CONSTRAINT "qr_print_jobs_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");



ALTER TABLE ONLY "public"."recipient_registrations"
    ADD CONSTRAINT "recipient_registrations_inventory_unit_id_fkey" FOREIGN KEY ("inventory_unit_id") REFERENCES "public"."inventory_units"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."recipient_registrations"
    ADD CONSTRAINT "recipient_registrations_registered_country_iso2_fkey" FOREIGN KEY ("registered_country_iso2") REFERENCES "public"."countries"("iso2");



ALTER TABLE ONLY "public"."shipments"
    ADD CONSTRAINT "shipments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."stock_batches"
    ADD CONSTRAINT "stock_batches_card_design_id_fkey" FOREIGN KEY ("card_design_id") REFERENCES "public"."card_designs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Admins can delete feature flags" ON "public"."feature_flags" FOR DELETE TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can insert feature flags" ON "public"."feature_flags" FOR INSERT TO "authenticated" WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage all order items" ON "public"."order_items" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage all orders" ON "public"."orders" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage all postcards" ON "public"."postcards" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage all shipments" ON "public"."shipments" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage card_design_images" ON "public"."card_design_images" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage card_designs" ON "public"."card_designs" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage card_language_templates" ON "public"."card_language_templates" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage countries" ON "public"."countries" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage events" ON "public"."inventory_unit_events" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage inventory_units" ON "public"."inventory_units" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage notifications" ON "public"."notifications" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage qr_print_job_items" ON "public"."qr_print_job_items" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage qr_print_jobs" ON "public"."qr_print_jobs" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage registrations" ON "public"."recipient_registrations" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage roles" ON "public"."user_roles" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage stock_batches" ON "public"."stock_batches" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can update feature flags" ON "public"."feature_flags" FOR UPDATE TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can update platform stats" ON "public"."platform_stats" FOR UPDATE TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can view all profiles" ON "public"."profiles" FOR SELECT TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins can view all roles" ON "public"."user_roles" FOR SELECT TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Admins manage categories" ON "public"."categories" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Allow read gamification_config to everyone" ON "public"."gamification_config" FOR SELECT USING (true);



CREATE POLICY "Allow read gamification_tiers to everyone" ON "public"."gamification_tiers" FOR SELECT USING (true);



CREATE POLICY "Allow update gamification_config to admins" ON "public"."gamification_config" FOR UPDATE TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Allow write gamification_tiers to admins" ON "public"."gamification_tiers" TO "authenticated" USING ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role")) WITH CHECK ("public"."has_role"("auth"."uid"(), 'admin'::"public"."app_role"));



CREATE POLICY "Anyone can read feature flags" ON "public"."feature_flags" FOR SELECT USING (true);



CREATE POLICY "Categories are viewable by everyone" ON "public"."categories" FOR SELECT USING (true);



CREATE POLICY "Everyone can view card_language_templates" ON "public"."card_language_templates" FOR SELECT USING (true);



CREATE POLICY "Platform stats are viewable by everyone" ON "public"."platform_stats" FOR SELECT USING (true);



CREATE POLICY "Public can view active countries" ON "public"."countries" FOR SELECT USING (("active" = true));



CREATE POLICY "Public can view active designs" ON "public"."card_designs" FOR SELECT USING (("active" = true));



CREATE POLICY "Public can view images of active designs" ON "public"."card_design_images" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."card_designs" "cd"
  WHERE (("cd"."id" = "card_design_images"."card_design_id") AND ("cd"."active" = true)))));



CREATE POLICY "Travelers can view own unit events" ON "public"."inventory_unit_events" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."inventory_units" "iu"
  WHERE (("iu"."id" = "inventory_unit_events"."inventory_unit_id") AND ("iu"."traveler_user_id" = "auth"."uid"())))));



CREATE POLICY "Travelers can view own units" ON "public"."inventory_units" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "traveler_user_id"));



CREATE POLICY "Users can insert their own profile" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own notifications" ON "public"."notifications" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update their own profile" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own notifications" ON "public"."notifications" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own order items" ON "public"."order_items" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."orders"
  WHERE (("orders"."id" = "order_items"."order_id") AND ("orders"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can view own orders" ON "public"."orders" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own profile" ON "public"."profiles" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own shipments" ON "public"."shipments" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view their own roles" ON "public"."user_roles" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."card_design_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."card_designs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."card_language_templates" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."countries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feature_flags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."gamification_config" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."gamification_tiers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."inventory_unit_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."inventory_units" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."order_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."platform_stats" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."postcards" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."qr_print_job_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."qr_print_jobs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recipient_registrations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."shipments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stock_batches" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_roles" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."recipient_registrations" TO "anon";
GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."recipient_registrations" TO "authenticated";
GRANT ALL ON TABLE "public"."recipient_registrations" TO "service_role";



GRANT SELECT("id") ON TABLE "public"."recipient_registrations" TO "authenticated";



GRANT SELECT("inventory_unit_id") ON TABLE "public"."recipient_registrations" TO "authenticated";



GRANT SELECT("recipient_name") ON TABLE "public"."recipient_registrations" TO "authenticated";



GRANT SELECT("recipient_message") ON TABLE "public"."recipient_registrations" TO "authenticated";



GRANT SELECT("contact_opt_in") ON TABLE "public"."recipient_registrations" TO "authenticated";



GRANT SELECT("registered_at") ON TABLE "public"."recipient_registrations" TO "authenticated";



GRANT SELECT("created_at") ON TABLE "public"."recipient_registrations" TO "authenticated";



REVOKE ALL ON FUNCTION "public"."admin_list_recipient_registrations"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."admin_list_recipient_registrations"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."calculate_distance"("lat1" numeric, "lon1" numeric, "lat2" numeric, "lon2" numeric) FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."calculate_distance"("lat1" numeric, "lon1" numeric, "lat2" numeric, "lon2" numeric) TO "authenticated";
GRANT ALL ON FUNCTION "public"."calculate_distance"("lat1" numeric, "lon1" numeric, "lat2" numeric, "lon2" numeric) TO "service_role";



REVOKE ALL ON FUNCTION "public"."calculate_user_impact_points"("_user_id" "uuid") FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."calculate_user_impact_points"("_user_id" "uuid") TO "service_role";



REVOKE ALL ON FUNCTION "public"."create_order"("_items" "jsonb", "_pickup_point_name" "text", "_pickup_point_address" "text", "_pickup_point_city" "text", "_shipping_cost" numeric, "_invoice_requested" boolean, "_company_name" "text", "_company_nip" "text", "_company_address" "text", "_payment_method" "text", "_shipping_method" "text", "_shipping_name" "text", "_shipping_street" "text", "_shipping_postal_code" "text", "_shipping_city" "text", "_shipping_phone" "text") FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."create_order"("_items" "jsonb", "_pickup_point_name" "text", "_pickup_point_address" "text", "_pickup_point_city" "text", "_shipping_cost" numeric, "_invoice_requested" boolean, "_company_name" "text", "_company_nip" "text", "_company_address" "text", "_payment_method" "text", "_shipping_method" "text", "_shipping_name" "text", "_shipping_street" "text", "_shipping_postal_code" "text", "_shipping_city" "text", "_shipping_phone" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_order"("_items" "jsonb", "_pickup_point_name" "text", "_pickup_point_address" "text", "_pickup_point_city" "text", "_shipping_cost" numeric, "_invoice_requested" boolean, "_company_name" "text", "_company_nip" "text", "_company_address" "text", "_payment_method" "text", "_shipping_method" "text", "_shipping_name" "text", "_shipping_street" "text", "_shipping_postal_code" "text", "_shipping_city" "text", "_shipping_phone" "text") TO "service_role";



REVOKE ALL ON FUNCTION "public"."generate_claim_code"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."generate_claim_code"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."generate_order_number"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."generate_order_number"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."generate_tracking_code"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."generate_tracking_code"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."handle_new_user"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."has_role"("_user_id" "uuid", "_role" "public"."app_role") TO "service_role";



GRANT ALL ON FUNCTION "public"."is_valid_nip"("_nip" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."is_valid_nip"("_nip" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_valid_nip"("_nip" "text") TO "service_role";



REVOKE ALL ON FUNCTION "public"."log_inventory_unit_event"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."log_inventory_unit_event"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."notify_on_new_registration"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."notify_on_new_registration"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."notify_on_rank_change"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."notify_on_rank_change"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."on_inventory_unit_recalc_gamification"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."on_inventory_unit_recalc_gamification"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."on_registration_add_kilometers"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."on_registration_add_kilometers"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."on_registration_recalc_gamification"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."on_registration_recalc_gamification"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."on_shipment_shipped"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."on_shipment_shipped"() TO "service_role";



GRANT ALL ON FUNCTION "public"."prepare_pod_order"("_order_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."prepare_pod_order"("_order_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."prepare_pod_order"("_order_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."prepare_pod_order_after_payment"() TO "anon";
GRANT ALL ON FUNCTION "public"."prepare_pod_order_after_payment"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."prepare_pod_order_after_payment"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."recalculate_user_gamification"("_user_id" "uuid") FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."recalculate_user_gamification"("_user_id" "uuid") TO "service_role";



REVOKE ALL ON FUNCTION "public"."register_recipient"("_unit_id" "uuid", "_recipient_name" "text", "_recipient_message" "text", "_recipient_email" "text", "_contact_opt_in" boolean, "_latitude" numeric, "_longitude" numeric) FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."register_recipient"("_unit_id" "uuid", "_recipient_name" "text", "_recipient_message" "text", "_recipient_email" "text", "_contact_opt_in" boolean, "_latitude" numeric, "_longitude" numeric) TO "service_role";



REVOKE ALL ON FUNCTION "public"."register_recipient"("_unit_id" "uuid", "_recipient_name" "text", "_recipient_message" "text", "_recipient_email" "text", "_contact_opt_in" boolean, "_latitude" numeric, "_longitude" numeric, "_registered_country_iso2" "text") FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."register_recipient"("_unit_id" "uuid", "_recipient_name" "text", "_recipient_message" "text", "_recipient_email" "text", "_contact_opt_in" boolean, "_latitude" numeric, "_longitude" numeric, "_registered_country_iso2" "text") TO "service_role";



REVOKE ALL ON FUNCTION "public"."reserve_inventory_for_order"("_order_id" "uuid") FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."reserve_inventory_for_order"("_order_id" "uuid") TO "service_role";



REVOKE ALL ON FUNCTION "public"."update_country_count"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."update_country_count"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_member_count"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_member_count"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_member_count"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_platform_stats_on_postcard"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_platform_stats_on_postcard"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_platform_stats_on_postcard"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."update_platform_stats_on_postcard_v2"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."update_platform_stats_on_postcard_v2"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_profile_stats_on_postcard"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_profile_stats_on_postcard"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_profile_stats_on_postcard"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."update_profile_stats_on_postcard_v2"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."update_profile_stats_on_postcard_v2"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";



GRANT ALL ON FUNCTION "public"."validate_postcard_status"() TO "anon";
GRANT ALL ON FUNCTION "public"."validate_postcard_status"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."validate_postcard_status"() TO "service_role";



GRANT ALL ON FUNCTION "public"."validate_profile_input"() TO "anon";
GRANT ALL ON FUNCTION "public"."validate_profile_input"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."validate_profile_input"() TO "service_role";



GRANT ALL ON FUNCTION "public"."validate_registration_input"() TO "anon";
GRANT ALL ON FUNCTION "public"."validate_registration_input"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."validate_registration_input"() TO "service_role";



GRANT ALL ON TABLE "public"."card_design_images" TO "anon";
GRANT ALL ON TABLE "public"."card_design_images" TO "authenticated";
GRANT ALL ON TABLE "public"."card_design_images" TO "service_role";



GRANT ALL ON TABLE "public"."card_designs" TO "anon";
GRANT ALL ON TABLE "public"."card_designs" TO "authenticated";
GRANT ALL ON TABLE "public"."card_designs" TO "service_role";



GRANT ALL ON TABLE "public"."card_language_templates" TO "anon";
GRANT ALL ON TABLE "public"."card_language_templates" TO "authenticated";
GRANT ALL ON TABLE "public"."card_language_templates" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON TABLE "public"."countries" TO "anon";
GRANT ALL ON TABLE "public"."countries" TO "authenticated";
GRANT ALL ON TABLE "public"."countries" TO "service_role";



GRANT ALL ON TABLE "public"."feature_flags" TO "anon";
GRANT ALL ON TABLE "public"."feature_flags" TO "authenticated";
GRANT ALL ON TABLE "public"."feature_flags" TO "service_role";



GRANT ALL ON TABLE "public"."gamification_config" TO "anon";
GRANT ALL ON TABLE "public"."gamification_config" TO "authenticated";
GRANT ALL ON TABLE "public"."gamification_config" TO "service_role";



GRANT ALL ON TABLE "public"."gamification_tiers" TO "anon";
GRANT ALL ON TABLE "public"."gamification_tiers" TO "authenticated";
GRANT ALL ON TABLE "public"."gamification_tiers" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."inventory_unit_events" TO "anon";
GRANT ALL ON TABLE "public"."inventory_unit_events" TO "authenticated";
GRANT ALL ON TABLE "public"."inventory_unit_events" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."inventory_units" TO "anon";
GRANT ALL ON TABLE "public"."inventory_units" TO "authenticated";
GRANT ALL ON TABLE "public"."inventory_units" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."order_items" TO "anon";
GRANT ALL ON TABLE "public"."order_items" TO "authenticated";
GRANT ALL ON TABLE "public"."order_items" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."orders" TO "anon";
GRANT ALL ON TABLE "public"."orders" TO "authenticated";
GRANT ALL ON TABLE "public"."orders" TO "service_role";



GRANT ALL ON TABLE "public"."platform_stats" TO "anon";
GRANT ALL ON TABLE "public"."platform_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."platform_stats" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."postcards" TO "anon";
GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."postcards" TO "authenticated";
GRANT ALL ON TABLE "public"."postcards" TO "service_role";



GRANT SELECT("id") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("design_id") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("serial_number") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("qr_token") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("status") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("buyer_id") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("buyer_display_name") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("purchased_at") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("order_reference") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("registered_at") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("created_at") ON TABLE "public"."postcards" TO "authenticated";



GRANT SELECT("updated_at") ON TABLE "public"."postcards" TO "authenticated";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."profiles_public" TO "anon";
GRANT ALL ON TABLE "public"."profiles_public" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles_public" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."qr_print_job_items" TO "anon";
GRANT ALL ON TABLE "public"."qr_print_job_items" TO "authenticated";
GRANT ALL ON TABLE "public"."qr_print_job_items" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."qr_print_jobs" TO "anon";
GRANT ALL ON TABLE "public"."qr_print_jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."qr_print_jobs" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."shipments" TO "anon";
GRANT ALL ON TABLE "public"."shipments" TO "authenticated";
GRANT ALL ON TABLE "public"."shipments" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."stock_batches" TO "anon";
GRANT ALL ON TABLE "public"."stock_batches" TO "authenticated";
GRANT ALL ON TABLE "public"."stock_batches" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."traveler_registrations_view" TO "anon";
GRANT ALL ON TABLE "public"."traveler_registrations_view" TO "authenticated";
GRANT ALL ON TABLE "public"."traveler_registrations_view" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."user_gamification_stats" TO "anon";
GRANT ALL ON TABLE "public"."user_gamification_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."user_gamification_stats" TO "service_role";



GRANT INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE "public"."user_roles" TO "anon";
GRANT ALL ON TABLE "public"."user_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_roles" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
